---
development:
  cloud_name: naemcivic
  api_key: ENV['cloudinary_api_key']
  api_secret: 5xw7HvgUoPiaAcStv8MMVh9d4I8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: naemcivic
  api_key: '525598947838827'
  api_secret: 5xw7HvgUoPiaAcStv8MMVh9d4I8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: naemcivic
  api_key: '525598947838827'
  api_secret: 5xw7HvgUoPiaAcStv8MMVh9d4I8
  enhance_image_tag: true
  static_image_support: false
